# Generated by Django 2.1.4 on 2018-12-13 18:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=20)),
                ('item', models.CharField(max_length=20, unique=True)),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2018, 12, 14, 3, 55, 33, 800878), max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('answer', models.CharField(max_length=20)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checklist.Checklist')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=20)),
                ('item', models.CharField(max_length=20)),
                ('date_from', models.DateTimeField(default=datetime.datetime(2018, 12, 14, 3, 55, 33, 799386), max_length=20)),
                ('date_to', models.DateTimeField(default=datetime.datetime(2018, 12, 14, 3, 55, 33, 799937), max_length=20)),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2018, 12, 14, 3, 55, 33, 799996), max_length=20)),
            ],
        ),
    ]
