# Generated by Django 2.1.4 on 2018-12-13 20:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=20)),
                ('item_img', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='checklist',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 14, 5, 2, 24, 668708), max_length=20),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date_from',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 14, 5, 2, 24, 667730), max_length=20),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date_to',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 14, 5, 2, 24, 667783), max_length=20),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 14, 5, 2, 24, 667820), max_length=20),
        ),
    ]
