# Generated by Django 2.1.4 on 2018-12-19 07:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0002_auto_20181214_0502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='date_from',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='date_to',
        ),
        migrations.AddField(
            model_name='reservation',
            name='end_datetime',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 19, 16, 32, 39, 397467), unique=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='end_time',
            field=models.TimeField(default=datetime.time, max_length=20),
        ),
        migrations.AddField(
            model_name='reservation',
            name='item_id',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='reservation',
            name='reserved_date',
            field=models.DateField(default=datetime.date(2018, 12, 19)),
        ),
        migrations.AddField(
            model_name='reservation',
            name='start_datetime',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 19, 16, 32, 39, 397441), unique=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='start_time',
            field=models.TimeField(default=datetime.time, max_length=20),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 19, 16, 32, 39, 398202), max_length=20),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 19, 16, 32, 39, 397491), max_length=20),
        ),
    ]
