# Generated by Django 2.1.4 on 2018-12-20 07:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0003_auto_20181219_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='question',
            name='checklist',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='start_time',
        ),
        migrations.AddField(
            model_name='question',
            name='item',
            field=models.CharField(default='Things', max_length=20),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='end_datetime',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 20, 16, 29, 35, 831336), unique=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 20, 16, 29, 35, 831357), max_length=20),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reserved_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='start_datetime',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 20, 16, 29, 35, 831308), unique=True),
        ),
        migrations.DeleteModel(
            name='Checklist',
        ),
    ]
