# Generated by Django 2.1.4 on 2018-12-20 07:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0004_auto_20181220_1629'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CheckListOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CheckListType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('options', models.ManyToManyField(to='checklist.CheckListOption')),
            ],
        ),
        migrations.AlterField(
            model_name='reservation',
            name='end_datetime',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 20, 16, 51, 26, 900767), unique=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 20, 16, 51, 26, 900785), max_length=20),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='start_datetime',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 20, 16, 51, 26, 900741), unique=True),
        ),
        migrations.AddField(
            model_name='checklist',
            name='checklist_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checklist.CheckListType'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='options',
            field=models.ManyToManyField(blank=True, to='checklist.CheckListOption'),
        ),
    ]
