# Generated by Django 2.1.4 on 2018-12-20 11:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0005_auto_20181220_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklisttype',
            name='options',
        ),
        migrations.RemoveField(
            model_name='checklist',
            name='checklist_type',
        ),
        migrations.RemoveField(
            model_name='checklist',
            name='name',
        ),
        migrations.RemoveField(
            model_name='checklist',
            name='options',
        ),
        migrations.AddField(
            model_name='checklist',
            name='answer',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='checklist',
            name='author',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='checklist',
            name='item_id',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='checklist',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 20, 20, 23, 54, 539343), max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checklist.Equipments'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='end_datetime',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 20, 20, 23, 54, 538679), unique=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 20, 20, 23, 54, 538698), max_length=20),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='start_datetime',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 20, 20, 23, 54, 538653), unique=True),
        ),
        migrations.DeleteModel(
            name='CheckListOption',
        ),
        migrations.DeleteModel(
            name='CheckListType',
        ),
    ]
