# Generated by Django 2.1.4 on 2018-12-20 11:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0006_auto_20181220_2023'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='item',
            new_name='item_name',
        ),
        migrations.RemoveField(
            model_name='equipments',
            name='item',
        ),
        migrations.RemoveField(
            model_name='question',
            name='item',
        ),
        migrations.AddField(
            model_name='checklist',
            name='item_name',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipments',
            name='item_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='answer',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='author',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='item_id',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 20, 20, 37, 6, 4181), max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='end_datetime',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 20, 20, 37, 6, 3641), unique=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='item_id',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 20, 20, 37, 6, 3659), max_length=20),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='start_datetime',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 20, 20, 37, 6, 3613), unique=True),
        ),
        migrations.AddField(
            model_name='equipments',
            name='item_category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='checklist.EquipmentCategory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='item_category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='checklist.EquipmentCategory'),
            preserve_default=False,
        ),
    ]
