# Generated by Django 2.1.4 on 2018-12-20 11:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0007_auto_20181220_2037'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=30)),
                ('item_img', models.ImageField(upload_to='')),
                ('item_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checklist.EquipmentCategory')),
            ],
        ),
        migrations.RemoveField(
            model_name='equipments',
            name='item_category',
        ),
        migrations.AlterField(
            model_name='checklist',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 20, 20, 43, 15, 961742), max_length=20),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='end_datetime',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 20, 20, 43, 15, 961158), unique=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 20, 20, 43, 15, 961177), max_length=20),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='start_datetime',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 20, 20, 43, 15, 961129), unique=True),
        ),
        migrations.DeleteModel(
            name='Equipments',
        ),
    ]
