# Generated by Django 2.1.4 on 2018-12-30 11:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0009_auto_20181220_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='reservation_id',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='checklist',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 30, 20, 30, 18, 784257), max_length=20),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='end_datetime',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 30, 20, 30, 18, 783713), unique=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 30, 20, 30, 18, 783730), max_length=20),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='start_datetime',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 30, 20, 30, 18, 783689), unique=True),
        ),
    ]
