# Generated by Django 2.1.4 on 2019-01-16 09:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0012_auto_20190105_0335'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='checklist_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 16, 18, 15, 30, 783911), max_length=20),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='end_datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 16, 18, 15, 30, 783245), unique=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 16, 18, 15, 30, 783283), max_length=20),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='start_datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 16, 18, 15, 30, 783218), unique=True),
        ),
    ]
